modLoader="javafml" 
loaderVersion="[24,)"
authors="xieao"
issueTrackerURL="http://www.minecraftforge.net/"

[[mods]]
modId="theora" 
version="${file.jarVersion}"
displayName="Theora" 
description='''
Theora mod.
'''