modLoader="javafml" 
loaderVersion="[24,)"
authors="xieao"

[[mods]] 
modId="theora" 
version="0.0.0.0"
displayName="Theora" 
description='''
Theora mod.
'''

[[dependencies.theora]]
    modId="onelib"
    mandatory=true
    versionRange="[0.0.0.0,)"
    ordering="NONE"
    side="BOTH"