modLoader="javafml" 
loaderVersion="[24,)"
authors="xieao"

[[mods]] 
modId="theora" 
version="0.0.0.0"
displayName="Theora" 
description='''
Theora mod.
'''

#[[dependencies.theora]]
#    modId="forge"
#    mandatory=false
#    versionRange="[24.0.81,)"
#    ordering="NONE"
#    side="BOTH"