modLoader="javafml" 
loaderVersion="[26,)"

[[mods]]
modId="theora" 
version="${file.jarVersion}"
displayName="Theora" 
authors="xieao"
description='''
Theora mod.
'''

#[[dependencies.theora]]
#    modId="lollipop"
#    mandatory=true
#    versionRange="[0.0.1,)"
#    ordering="NONE"
#    side="BOTH"